# Generated by Django 5.2.1 on 2025-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemate',
            name='average_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coursemate',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
